name: Nu Module Test 2

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/module
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: nu {0}

jobs:
  test-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
        ver: [0.85]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, nu@${{matrix.ver}})
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Setup nu@latest
      uses: hustcer/setup-nu@feature/module
      with:
        enable-plugins: true
        version: ${{matrix.ver}}
      env:
        ACTIONS_STEP_DEBUG: true
        NU_MODULE_DIRS: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Your Nu Modules
      run: |
        use ./nu/module.nu *
        print (get-env 'ABC-XYZ' 'DEFAULT-ABC-XYZ')
