name: run-test

on:
  push:
    branches:
      - main
      - develop
      - release/*
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: nu {0}

jobs:
  test-latest:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, nu@latest)
    steps:
    - uses: actions/checkout@v3
    - name: Setup nu@latest
      uses: hustcer/setup-nu@develop
      with:
        check-latest: true
        enable-plugins: true
      env:
        ACTIONS_STEP_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: You can run bash commands, too
      run: pwd && ls -la
      shell: bash
    - name: Default shell will be `nu`
      run: |
        print $'Nu version info:(char nl)'; version
        print $'Current env:(char nl)'; $env
        print $'Nu path:(which nu)(char nl)'
        print $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
        def greeting [name: string] {
          print $'Hello ($name)'
        }
        greeting hustcer

  test-ver:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: test (${{matrix.os}}, nu@latest)
    steps:
    - uses: actions/checkout@v3
    - name: Setup nu@latest
      uses: hustcer/setup-nu@v3.2
      with:
        version: 0.78
        enable-plugins: true
      env:
        ACTIONS_STEP_DEBUG: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: print $'Nu version info:(char nl)'; version
    - run: print $'Current env:(char nl)'; $env
    - run: print $'Nu path:(which nu)(char nl)'
    - run: print $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
